// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        (unknown)
// source: rta/v1/view.proto

// Package rta.v1 is the wire form of the capability contract: what a plugin
// declares, what a host asks it to do, and what comes back.
//
// It mirrors pkg/view and pkg/plugin deliberately and not accidentally. The
// Go types are the contract an in-process built-in implements, and this is
// the same contract for a subprocess — a built-in and a plugin
// implement the same interface, so a difference between these two files and
// those packages is a bug in one of them, never a design.
//
// Freeze rules for v1, in force from the moment the first third-party plugin
// exists:
//
//   - Field numbers are assigned once. A removed field is `reserved`, never
//     reused, and never renumbered.
//   - Enum values are appended. The zero value of every enum is
//     *_UNSPECIFIED and means "the sender did not say", which is an error at
//     the receiving end rather than a default — the same decision Field.Type
//     made in Go, for the same reason.
//   - New optional fields may be added. Anything that changes the meaning of
//     an existing one is v2.

package rtav1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ColumnKind is a semantic hint for formatting and alignment. It never
// prescribes styling: how a percentage is drawn belongs to the host.
type ColumnKind int32

const (
	// Unspecified means plain text, and is the common case: a column with
	// nothing special about it. This is the one enum here whose zero value is
	// meaningful rather than an omission, and it matches the Go contract
	// exactly, where KindText is the empty string.
	ColumnKind_COLUMN_KIND_UNSPECIFIED ColumnKind = 0
	ColumnKind_COLUMN_KIND_NUMBER      ColumnKind = 1
	ColumnKind_COLUMN_KIND_BYTES       ColumnKind = 2
	ColumnKind_COLUMN_KIND_PERCENT     ColumnKind = 3
	ColumnKind_COLUMN_KIND_DURATION    ColumnKind = 4
	ColumnKind_COLUMN_KIND_TIMESTAMP   ColumnKind = 5
	ColumnKind_COLUMN_KIND_STATUS      ColumnKind = 6
	// How much of a capacity is taken, as a percentage, where approaching 100
	// is approaching a limit. Distinct from PERCENT, which is any proportion
	// and says nothing about which end is the bad one: a directory's share of
	// a disk is not a problem for being large, and a process past 100% CPU is
	// on a second core. A host may grade this one; where the bands are is in
	// the Go contract beside the kind, and what a band looks like is still the
	// host's.
	ColumnKind_COLUMN_KIND_USAGE ColumnKind = 7
)

// Enum value maps for ColumnKind.
var (
	ColumnKind_name = map[int32]string{
		0: "COLUMN_KIND_UNSPECIFIED",
		1: "COLUMN_KIND_NUMBER",
		2: "COLUMN_KIND_BYTES",
		3: "COLUMN_KIND_PERCENT",
		4: "COLUMN_KIND_DURATION",
		5: "COLUMN_KIND_TIMESTAMP",
		6: "COLUMN_KIND_STATUS",
		7: "COLUMN_KIND_USAGE",
	}
	ColumnKind_value = map[string]int32{
		"COLUMN_KIND_UNSPECIFIED": 0,
		"COLUMN_KIND_NUMBER":      1,
		"COLUMN_KIND_BYTES":       2,
		"COLUMN_KIND_PERCENT":     3,
		"COLUMN_KIND_DURATION":    4,
		"COLUMN_KIND_TIMESTAMP":   5,
		"COLUMN_KIND_STATUS":      6,
		"COLUMN_KIND_USAGE":       7,
	}
)

func (x ColumnKind) Enum() *ColumnKind {
	p := new(ColumnKind)
	*p = x
	return p
}

func (x ColumnKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColumnKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rta_v1_view_proto_enumTypes[0].Descriptor()
}

func (ColumnKind) Type() protoreflect.EnumType {
	return &file_rta_v1_view_proto_enumTypes[0]
}

func (x ColumnKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColumnKind.Descriptor instead.
func (ColumnKind) EnumDescriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{0}
}

type ChartKind int32

const (
	ChartKind_CHART_KIND_UNSPECIFIED ChartKind = 0
	// Each series is a sequence of points.
	ChartKind_CHART_KIND_LINE ChartKind = 1
	// Each series is one labelled value.
	ChartKind_CHART_KIND_BAR ChartKind = 2
)

// Enum value maps for ChartKind.
var (
	ChartKind_name = map[int32]string{
		0: "CHART_KIND_UNSPECIFIED",
		1: "CHART_KIND_LINE",
		2: "CHART_KIND_BAR",
	}
	ChartKind_value = map[string]int32{
		"CHART_KIND_UNSPECIFIED": 0,
		"CHART_KIND_LINE":        1,
		"CHART_KIND_BAR":         2,
	}
)

func (x ChartKind) Enum() *ChartKind {
	p := new(ChartKind)
	*p = x
	return p
}

func (x ChartKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChartKind) Descriptor() protoreflect.EnumDescriptor {
	return file_rta_v1_view_proto_enumTypes[1].Descriptor()
}

func (ChartKind) Type() protoreflect.EnumType {
	return &file_rta_v1_view_proto_enumTypes[1]
}

func (x ChartKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChartKind.Descriptor instead.
func (ChartKind) EnumDescriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{1}
}

// Error is the first-class error contract. Renderers show Message and Hint;
// an agent branches on Code.
type Error struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable and namespaced, e.g. "pg.conn.refused". Never rewritten by the
	// host: it is what scripts and agents branch on.
	Code      string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message   string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Hint      string `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
	Retryable bool   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	// A policy gate saying no to the caller's standing — not the work
	// breaking. The host's audit trail records a refusal and a failure as
	// different outcomes, and only the plugin knows which one it returned.
	Refusal       bool `protobuf:"varint,5,opt,name=refusal,proto3" json:"refusal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_rta_v1_view_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *Error) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *Error) GetRefusal() bool {
	if x != nil {
		return x.Refusal
	}
	return false
}

// Text is free-form text, optionally markdown for the host to render.
type Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	Markdown      bool                   `protobuf:"varint,2,opt,name=markdown,proto3" json:"markdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Text) Reset() {
	*x = Text{}
	mi := &file_rta_v1_view_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{1}
}

func (x *Text) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Text) GetMarkdown() bool {
	if x != nil {
		return x.Markdown
	}
	return false
}

// Pair is one labelled value.
type Pair struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pair) Reset() {
	*x = Pair{}
	mi := &file_rta_v1_view_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pair) ProtoMessage() {}

func (x *Pair) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pair.ProtoReflect.Descriptor instead.
func (*Pair) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{2}
}

func (x *Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// KeyValue is a flat set of labelled values.
type KeyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Pairs []*Pair                `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
	// Keys whose values every renderer must mask. Names rather than indices,
	// so reordering cannot move the protection to the wrong entry.
	Redacted      []string `protobuf:"bytes,2,rep,name=redacted,proto3" json:"redacted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_rta_v1_view_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{3}
}

func (x *KeyValue) GetPairs() []*Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

func (x *KeyValue) GetRedacted() []string {
	if x != nil {
		return x.Redacted
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind          ColumnKind             `protobuf:"varint,2,opt,name=kind,proto3,enum=rta.v1.ColumnKind" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_rta_v1_view_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{4}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetKind() ColumnKind {
	if x != nil {
		return x.Kind
	}
	return ColumnKind_COLUMN_KIND_UNSPECIFIED
}

// Cursor carries contract-level pagination state.
type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          string                 `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_rta_v1_view_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{5}
}

func (x *Cursor) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

// Row exists because proto3 has no repeated-of-repeated. It is not a concept
// in the Go contract and hosts should not surface it as one.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []string               `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_rta_v1_view_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{6}
}

func (x *Row) GetCells() []string {
	if x != nil {
		return x.Cells
	}
	return nil
}

// Table is tabular data with pre-formatted cells.
type Table struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Columns []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	Rows    []*Row                 `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	// How many rows exist overall, >= len(rows) when paginated. Zero means
	// "not paginated", not "no rows".
	Total int32   `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Page  *Cursor `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	// Column names whose cells every renderer must mask.
	Redacted []string `protobuf:"bytes,5,rep,name=redacted,proto3" json:"redacted,omitempty"`
	// The rows are in time order and the newest is last, so a surface that
	// scrolls opens at the end: a log is read from where it is now, back.
	Tail          bool `protobuf:"varint,6,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Table) Reset() {
	*x = Table{}
	mi := &file_rta_v1_view_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Table) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Table) ProtoMessage() {}

func (x *Table) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Table.ProtoReflect.Descriptor instead.
func (*Table) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{7}
}

func (x *Table) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

func (x *Table) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *Table) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Table) GetPage() *Cursor {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *Table) GetRedacted() []string {
	if x != nil {
		return x.Redacted
	}
	return nil
}

func (x *Table) GetTail() bool {
	if x != nil {
		return x.Tail
	}
	return false
}

type Series struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Points        []float64              `protobuf:"fixed64,2,rep,packed,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Series) Reset() {
	*x = Series{}
	mi := &file_rta_v1_view_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Series) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Series) ProtoMessage() {}

func (x *Series) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Series.ProtoReflect.Descriptor instead.
func (*Series) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{8}
}

func (x *Series) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Series) GetPoints() []float64 {
	if x != nil {
		return x.Points
	}
	return nil
}

type Chart struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Kind   ChartKind              `protobuf:"varint,1,opt,name=kind,proto3,enum=rta.v1.ChartKind" json:"kind,omitempty"`
	Series []*Series              `protobuf:"bytes,2,rep,name=series,proto3" json:"series,omitempty"`
	// Annotates values, e.g. "ms" or "%".
	Unit string `protobuf:"bytes,3,opt,name=unit,proto3" json:"unit,omitempty"`
	// When > 0, fixes the top of the scale so two renders of the same metric
	// can be compared. It belongs to the chart and not to each series, because
	// the series share one axis — see pkg/view for what the per-series version
	// silently got wrong.
	Max           float64 `protobuf:"fixed64,4,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chart) Reset() {
	*x = Chart{}
	mi := &file_rta_v1_view_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chart) ProtoMessage() {}

func (x *Chart) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chart.ProtoReflect.Descriptor instead.
func (*Chart) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{9}
}

func (x *Chart) GetKind() ChartKind {
	if x != nil {
		return x.Kind
	}
	return ChartKind_CHART_KIND_UNSPECIFIED
}

func (x *Chart) GetSeries() []*Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *Chart) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

func (x *Chart) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Detail        string                 `protobuf:"bytes,2,opt,name=detail,proto3" json:"detail,omitempty"`
	Children      []*Node                `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_rta_v1_view_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{10}
}

func (x *Node) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Node) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Node) GetChildren() []*Node {
	if x != nil {
		return x.Children
	}
	return nil
}

type Tree struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roots         []*Node                `protobuf:"bytes,1,rep,name=roots,proto3" json:"roots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tree) Reset() {
	*x = Tree{}
	mi := &file_rta_v1_view_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tree) ProtoMessage() {}

func (x *Tree) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tree.ProtoReflect.Descriptor instead.
func (*Tree) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{11}
}

func (x *Tree) GetRoots() []*Node {
	if x != nil {
		return x.Roots
	}
	return nil
}

// Section is one titled part of a composite view.
type Section struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable identifier a script or an agent addresses the section by.
	// Optional; the host falls back to title. It exists so that rewording a
	// heading is UX work rather than a silent breaking change.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	View          *View  `protobuf:"bytes,3,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_rta_v1_view_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{12}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

// Sections is a composite page.
type Sections struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Items []*Section             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// What the page could not produce. A partial page must say it is partial:
	// a dropped section leaves no trace, so a degraded page and a whole one
	// are otherwise indistinguishable.
	Warnings      []*Error `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sections) Reset() {
	*x = Sections{}
	mi := &file_rta_v1_view_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sections) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sections) ProtoMessage() {}

func (x *Sections) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sections.ProtoReflect.Descriptor instead.
func (*Sections) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{13}
}

func (x *Sections) GetItems() []*Section {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Sections) GetWarnings() []*Error {
	if x != nil {
		return x.Warnings
	}
	return nil
}

// View is the closed union of result types a capability can return.
//
// An unset oneof is legal and means "nothing to show" — a handler returning
// no view, or a Section carrying a title and nothing under it. Every renderer
// skips it rather than treating it as an error.
type View struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*View_Text
	//	*View_KeyValue
	//	*View_Table
	//	*View_Tree
	//	*View_Chart
	//	*View_Sections
	//	*View_Error
	Kind          isView_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_rta_v1_view_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_rta_v1_view_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_rta_v1_view_proto_rawDescGZIP(), []int{14}
}

func (x *View) GetKind() isView_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *View) GetText() *Text {
	if x != nil {
		if x, ok := x.Kind.(*View_Text); ok {
			return x.Text
		}
	}
	return nil
}

func (x *View) GetKeyValue() *KeyValue {
	if x != nil {
		if x, ok := x.Kind.(*View_KeyValue); ok {
			return x.KeyValue
		}
	}
	return nil
}

func (x *View) GetTable() *Table {
	if x != nil {
		if x, ok := x.Kind.(*View_Table); ok {
			return x.Table
		}
	}
	return nil
}

func (x *View) GetTree() *Tree {
	if x != nil {
		if x, ok := x.Kind.(*View_Tree); ok {
			return x.Tree
		}
	}
	return nil
}

func (x *View) GetChart() *Chart {
	if x != nil {
		if x, ok := x.Kind.(*View_Chart); ok {
			return x.Chart
		}
	}
	return nil
}

func (x *View) GetSections() *Sections {
	if x != nil {
		if x, ok := x.Kind.(*View_Sections); ok {
			return x.Sections
		}
	}
	return nil
}

func (x *View) GetError() *Error {
	if x != nil {
		if x, ok := x.Kind.(*View_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isView_Kind interface {
	isView_Kind()
}

type View_Text struct {
	Text *Text `protobuf:"bytes,1,opt,name=text,proto3,oneof"`
}

type View_KeyValue struct {
	KeyValue *KeyValue `protobuf:"bytes,2,opt,name=key_value,json=keyValue,proto3,oneof"`
}

type View_Table struct {
	Table *Table `protobuf:"bytes,3,opt,name=table,proto3,oneof"`
}

type View_Tree struct {
	Tree *Tree `protobuf:"bytes,4,opt,name=tree,proto3,oneof"`
}

type View_Chart struct {
	Chart *Chart `protobuf:"bytes,5,opt,name=chart,proto3,oneof"`
}

type View_Sections struct {
	Sections *Sections `protobuf:"bytes,6,opt,name=sections,proto3,oneof"`
}

type View_Error struct {
	Error *Error `protobuf:"bytes,7,opt,name=error,proto3,oneof"`
}

func (*View_Text) isView_Kind() {}

func (*View_KeyValue) isView_Kind() {}

func (*View_Table) isView_Kind() {}

func (*View_Tree) isView_Kind() {}

func (*View_Chart) isView_Kind() {}

func (*View_Sections) isView_Kind() {}

func (*View_Error) isView_Kind() {}

var File_rta_v1_view_proto protoreflect.FileDescriptor

var file_rta_v1_view_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x72, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x76, 0x69, 0x65, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x05,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x74, 0x72, 0x79,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x74, 0x72,
	0x79, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x75, 0x73, 0x61, 0x6c,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x66, 0x75, 0x73, 0x61, 0x6c, 0x22,
	0x36, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6d,
	0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x6d,
	0x61, 0x72, 0x6b, 0x64, 0x6f, 0x77, 0x6e, 0x22, 0x2e, 0x0a, 0x04, 0x50, 0x61, 0x69, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x4a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x69, 0x72,
	0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x61, 0x63,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x61, 0x63,
	0x74, 0x65, 0x64, 0x22, 0x44, 0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x26, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x12, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x22, 0x1c, 0x0a, 0x06, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x65, 0x78, 0x74, 0x22, 0x1b, 0x0a, 0x03, 0x52, 0x6f, 0x77, 0x12, 0x14,
	0x0a, 0x05, 0x63, 0x65, 0x6c, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x65, 0x6c, 0x6c, 0x73, 0x22, 0xbc, 0x01, 0x0a, 0x05, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x28,
	0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52,
	0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x12, 0x1f, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x6f, 0x77, 0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x12,
	0x22, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x52, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x64, 0x61, 0x63, 0x74, 0x65, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x74,
	0x61, 0x69, 0x6c, 0x22, 0x34, 0x0a, 0x06, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x01, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x7c, 0x0a, 0x05, 0x43, 0x68, 0x61,
	0x72, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x11, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x4b,
	0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x73, 0x65, 0x72,
	0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x72, 0x74, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x06, 0x73, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x75, 0x6e, 0x69, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x5e, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x28, 0x0a,
	0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x08, 0x63,
	0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22, 0x2a, 0x0a, 0x04, 0x54, 0x72, 0x65, 0x65, 0x12,
	0x22, 0x0a, 0x05, 0x72, 0x6f, 0x6f, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x05, 0x72, 0x6f,
	0x6f, 0x74, 0x73, 0x22, 0x51, 0x0a, 0x07, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x69, 0x74, 0x6c, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x76, 0x69, 0x65, 0x77, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x04, 0x76, 0x69, 0x65, 0x77, 0x22, 0x5c, 0x0a, 0x08, 0x53, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0f, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x29, 0x0a, 0x08, 0x77, 0x61, 0x72,
	0x6e, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x08, 0x77, 0x61, 0x72, 0x6e,
	0x69, 0x6e, 0x67, 0x73, 0x22, 0xac, 0x02, 0x0a, 0x04, 0x56, 0x69, 0x65, 0x77, 0x12, 0x22, 0x0a,
	0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x74,
	0x61, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x12, 0x2f, 0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x65,
	0x79, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x08, 0x6b, 0x65, 0x79, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x48, 0x00, 0x52, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x22, 0x0a, 0x04, 0x74, 0x72, 0x65,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31,
	0x2e, 0x54, 0x72, 0x65, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x72, 0x65, 0x65, 0x12, 0x25, 0x0a,
	0x05, 0x63, 0x68, 0x61, 0x72, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72,
	0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x05, 0x63,
	0x68, 0x61, 0x72, 0x74, 0x12, 0x2e, 0x0a, 0x08, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x08, 0x73, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x74, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x06, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x2a, 0xd5, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x4b, 0x69,
	0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4b, 0x49, 0x4e,
	0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12,
	0x16, 0x0a, 0x12, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4e,
	0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x01, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4c, 0x55, 0x4d,
	0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x42, 0x59, 0x54, 0x45, 0x53, 0x10, 0x02, 0x12, 0x17,
	0x0a, 0x13, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x50, 0x45,
	0x52, 0x43, 0x45, 0x4e, 0x54, 0x10, 0x03, 0x12, 0x18, 0x0a, 0x14, 0x43, 0x4f, 0x4c, 0x55, 0x4d,
	0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x44, 0x55, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0x04, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44,
	0x5f, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12,
	0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x10, 0x06, 0x12, 0x15, 0x0a, 0x11, 0x43, 0x4f, 0x4c, 0x55, 0x4d, 0x4e, 0x5f, 0x4b,
	0x49, 0x4e, 0x44, 0x5f, 0x55, 0x53, 0x41, 0x47, 0x45, 0x10, 0x07, 0x2a, 0x50, 0x0a, 0x09, 0x43,
	0x68, 0x61, 0x72, 0x74, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1a, 0x0a, 0x16, 0x43, 0x48, 0x41, 0x52,
	0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x43, 0x48, 0x41, 0x52, 0x54, 0x5f, 0x4b, 0x49,
	0x4e, 0x44, 0x5f, 0x4c, 0x49, 0x4e, 0x45, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x43, 0x48, 0x41,
	0x52, 0x54, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x42, 0x41, 0x52, 0x10, 0x02, 0x42, 0x30, 0x5a,
	0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x69, 0x73,
	0x2d, 0x69, 0x73, 0x2d, 0x74, 0x6f, 0x62, 0x69, 0x2f, 0x72, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x72, 0x74, 0x61, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x74, 0x61, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_rta_v1_view_proto_rawDescOnce sync.Once
	file_rta_v1_view_proto_rawDescData []byte
)

func file_rta_v1_view_proto_rawDescGZIP() []byte {
	file_rta_v1_view_proto_rawDescOnce.Do(func() {
		file_rta_v1_view_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rta_v1_view_proto_rawDesc), len(file_rta_v1_view_proto_rawDesc)))
	})
	return file_rta_v1_view_proto_rawDescData
}

var file_rta_v1_view_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rta_v1_view_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rta_v1_view_proto_goTypes = []any{
	(ColumnKind)(0),  // 0: rta.v1.ColumnKind
	(ChartKind)(0),   // 1: rta.v1.ChartKind
	(*Error)(nil),    // 2: rta.v1.Error
	(*Text)(nil),     // 3: rta.v1.Text
	(*Pair)(nil),     // 4: rta.v1.Pair
	(*KeyValue)(nil), // 5: rta.v1.KeyValue
	(*Column)(nil),   // 6: rta.v1.Column
	(*Cursor)(nil),   // 7: rta.v1.Cursor
	(*Row)(nil),      // 8: rta.v1.Row
	(*Table)(nil),    // 9: rta.v1.Table
	(*Series)(nil),   // 10: rta.v1.Series
	(*Chart)(nil),    // 11: rta.v1.Chart
	(*Node)(nil),     // 12: rta.v1.Node
	(*Tree)(nil),     // 13: rta.v1.Tree
	(*Section)(nil),  // 14: rta.v1.Section
	(*Sections)(nil), // 15: rta.v1.Sections
	(*View)(nil),     // 16: rta.v1.View
}
var file_rta_v1_view_proto_depIdxs = []int32{
	4,  // 0: rta.v1.KeyValue.pairs:type_name -> rta.v1.Pair
	0,  // 1: rta.v1.Column.kind:type_name -> rta.v1.ColumnKind
	6,  // 2: rta.v1.Table.columns:type_name -> rta.v1.Column
	8,  // 3: rta.v1.Table.rows:type_name -> rta.v1.Row
	7,  // 4: rta.v1.Table.page:type_name -> rta.v1.Cursor
	1,  // 5: rta.v1.Chart.kind:type_name -> rta.v1.ChartKind
	10, // 6: rta.v1.Chart.series:type_name -> rta.v1.Series
	12, // 7: rta.v1.Node.children:type_name -> rta.v1.Node
	12, // 8: rta.v1.Tree.roots:type_name -> rta.v1.Node
	16, // 9: rta.v1.Section.view:type_name -> rta.v1.View
	14, // 10: rta.v1.Sections.items:type_name -> rta.v1.Section
	2,  // 11: rta.v1.Sections.warnings:type_name -> rta.v1.Error
	3,  // 12: rta.v1.View.text:type_name -> rta.v1.Text
	5,  // 13: rta.v1.View.key_value:type_name -> rta.v1.KeyValue
	9,  // 14: rta.v1.View.table:type_name -> rta.v1.Table
	13, // 15: rta.v1.View.tree:type_name -> rta.v1.Tree
	11, // 16: rta.v1.View.chart:type_name -> rta.v1.Chart
	15, // 17: rta.v1.View.sections:type_name -> rta.v1.Sections
	2,  // 18: rta.v1.View.error:type_name -> rta.v1.Error
	19, // [19:19] is the sub-list for method output_type
	19, // [19:19] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_rta_v1_view_proto_init() }
func file_rta_v1_view_proto_init() {
	if File_rta_v1_view_proto != nil {
		return
	}
	file_rta_v1_view_proto_msgTypes[14].OneofWrappers = []any{
		(*View_Text)(nil),
		(*View_KeyValue)(nil),
		(*View_Table)(nil),
		(*View_Tree)(nil),
		(*View_Chart)(nil),
		(*View_Sections)(nil),
		(*View_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rta_v1_view_proto_rawDesc), len(file_rta_v1_view_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rta_v1_view_proto_goTypes,
		DependencyIndexes: file_rta_v1_view_proto_depIdxs,
		EnumInfos:         file_rta_v1_view_proto_enumTypes,
		MessageInfos:      file_rta_v1_view_proto_msgTypes,
	}.Build()
	File_rta_v1_view_proto = out.File
	file_rta_v1_view_proto_goTypes = nil
	file_rta_v1_view_proto_depIdxs = nil
}
